### ISSUE TITLE
Crypto prices doesn't change and the script crashes as well

### ISSUE THREAD

**Issue by Avngl** [KarlHlmgrn/crypto-oled#4]
Hi, i am not sure if this is normal or not but this is what happens when i launch the crypto-graphing.py script

1) The word 'btc' appears for a few seconds and then it dissappears. Nothing else appears on the oled panel.

2) I can then cycle between other crypto currencies however it still behaves the same as 1.

3) I can then move the "cursor" which is the graph and it'll show the time or percentage of the crypto. Moving it all towards the edge would then allow me to press another button that would display the current price of the crypto. The price remains and doesn't change despite waiting for more than a minute.

4) If i do cycle through other crypto, and press other buttons, the script would eventually crash with the error:

```
Traceback (most recent call last):
  File "C:\Users\myname\Downloads\oled\crypto-graphing.py", line 285, in <module>
    time = getTime(xvalue,graph[3],tz)
  File "C:\Users\myname\Downloads\oled\crypto-graphing.py", line 119, in getTime
    timeraw = data[xvalue][0]
IndexError: list index out of range
```

I made a video of this here: https://youtu.be/dGTTEawz8bQ

Using Windows 10.

**Comment by KarlHlmgrn** [comment]
Hi again, the issue seems to lie with the matplotlib dependency. After some debugging, I couldn't see why it's didn't work. About the price not changing it's because it's pulling data from the graph which updates every 5 minutes, I will change that so the last value of the graph will change every minute(hopefully). I am not able to replicate the crash but will also look into that.

**Comment by KarlHlmgrn** [comment]
Hi, good news! I have fixed everything except for the very rare crash. Will be looking into that in the near future!

Thanks for the help!

**Comment by Avngl** [comment]
Hi, Thank you for the quick fix.

I'll test and provide a feedback shortly.

**Comment by KarlHlmgrn** [comment]
@Avngl How's everything working so far?

**Comment by Avngl** [comment]
Thanks @KarlHlmgrn.

The graph shows up now and the price is updated every minute as expected.

The crash still occurs though.

1. Move the bar to the far right of the chart to show the latest price of the crypto.
2. Switch to another crypto and the crash occurs.

It doesn't happen all the time however the main issue has  been sorted out.

I don't see the graph moving though. Is it supposed to be like that? I am afraid of a potential 'burn-in' on the oled panel.

**Comment by KarlHlmgrn** [comment]
@Avngl The graph shows the last 24 hours so it's expected to not move much at all, but I suspect something in the code is wrong. I could also add anti-burn in while I'm at it.

I think I know why it's crashing,I will take a deeper look when I get back home.

**Comment by Avngl** [comment]
Thanks @KarlHlmgrn 

Also i noticed this happening a couple of times, quite frequently.

I chose the crypto that I want, and it starts updating every minute. After awhile, it crashes, and I see "Updating" on the oled screen.

![image](https://user-images.githubusercontent.com/36796461/139685609-c64cf971-71be-44fc-b1dd-653569f9d737.png)

```Traceback (most recent call last):
  File "C:\Users\myname\Downloads\oled\crypto-graphing.py", line 284, in <module>
    time = getTime(xvalue,graph[3],tz)
  File "C:\Users\myname\Downloads\oled\crypto-graphing.py", line 118, in getTime
    timeraw = data[xvalue][0]
IndexError: list index out of range```

**Comment by KarlHlmgrn** [comment]
@Avngl It's the same odd error as you encountered before but in a different environment. Were you looking at the time before that when you were looking at the graph?

**Comment by Avngl** [comment]
No @KarlHlmgrn. I left the chart as is and was watching a video. Did not use the keyboard much during that time, and did not use the hotkeys set for the chart. Basically it was left on its own.

When i remembered to check the chart, i then saw that it was stuck on "Updating" and the script has crashed. This happened a few times, all without me pressing anything to interact with the script.

**Comment by KarlHlmgrn** [comment]
@Avngl Really odd. Will fix the issue when I get back, stay put.

**Comment by Avngl** [comment]
Will do @KarlHlmgrn

**Comment by KarlHlmgrn** [comment]
@Avngl Check the latest commit and see if that changes anything, probably not but that is the only change I was able to come up with at the moment.

**Comment by KarlHlmgrn** [comment]
@Avngl The whole program is now re-written and I believe that the bug has been fixed, if not then just open a new issue and I will help you!
